format = """
╭─ \
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$python\
$golang\
$nodejs\
$docker_context\
$cmd_duration\
$line_break\
╰$character"""

[directory]
style = "blue"

# [character]
# success_symbol = "[❯](purple)"
# error_symbol = "[❯](red)"
# vimcmd_symbol = "[❮](green)"

[character]
disabled = false
success_symbol = '[\[I\]:](bold fg:color_orange)'
error_symbol = '[\[I\]:](bold fg:color_orange)'
vimcmd_symbol = '[\[N\]:](bold fg:color_orange)'
vimcmd_replace_one_symbol = '[\[R\]:](bold fg:color_orange)'
vimcmd_replace_symbol = '[\[R\]:](bold fg:color_orange)'
vimcmd_visual_symbol = '[\[V\]:](bold fg:color_orange)'

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style) "
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[docker_context]
symbol = ""
style = "bg:color_bg3"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[golang]
symbol = ""
style = "bright-black"
format = "[$symbol($version)]($style) "

[nodejs]
symbol = ""
style = "bright-black"
format = "[$symbol($version)]($style) "

[c]
symbol = " "
style = "bright-black"
format = "[$symbol($version)]($style) "

[rust]
symbol = ""
style = "bright-black"
format = "[$symbol($version)]($style) "

[php]
symbol = ""
style = "bright-black"
format = "[$symbol($version)]($style) "

[java]
symbol = " "
style = "bright-black"
format = "[$symbol($version)]($style) "

[kotlin]
symbol = ""
style = "bright-black"
format = "[$symbol($version)]($style) "

[haskell]
symbol = ""
style = "bright-black"
format = "[$symbol($version)]($style) "

[python]
symbol = ""
style = "bright-black"
format = "[$virtualenv]($style) "
